# Generated by Django 4.2.20 on 2025-04-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postskip',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='skip_photo', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='postskip',
            name='body',
            field=models.TextField(default='', verbose_name='이유'),
        ),
    ]
