# Generated by Django 5.2.1 on 2025-05-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='letter_photo', verbose_name='이미지'),
        ),
    ]
