# Generated by Django 5.2.1 on 2025-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delay_choice',
            field=models.CharField(choices=[('1d', '1일 후'), ('7d', '7일 후'), ('30d', '30일 후'), ('365d', '1년 후')], default='1d', max_length=5),
        ),
    ]
