# Generated by Django 4.2.20 on 2025-05-06 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_comment_like_users_note_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='scrap_users',
            field=models.ManyToManyField(related_name='scrap_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
