# Generated by Django 4.2.20 on 2025-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact_photo', verbose_name='이미지'),
        ),
    ]
