# Generated by Django 4.2.20 on 2025-03-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPick',
            new_name='Post',
        ),
    ]
