# Generated by Django 4.2.20 on 2025-03-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_rename_postpick_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostPick',
        ),
    ]
