# Generated by Django 5.1.7 on 2025-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=300, null=True, verbose_name='유튜브링크'),
        ),
    ]
