# Generated by Django 5.1.7 on 2025-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='유튜브링크'),
        ),
    ]
