# Generated by Django 5.1.7 on 2025-04-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='yourpick_photo', verbose_name='사진'),
        ),
    ]
