# Generated by Django 4.2.20 on 2025-05-05 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skips', '0005_skipcomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postskip',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='skip_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
