# Generated by Django 4.2.20 on 2025-05-06 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skips', '0006_postskip_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postskip',
            name='voter',
        ),
        migrations.AddField(
            model_name='postskip',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_skips', to=settings.AUTH_USER_MODEL),
        ),
    ]
