# Generated by Django 5.2.1 on 2025-05-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Guest',
        ),
    ]
