# Generated by Django 5.2.1 on 2025-05-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_rename_post_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='guest',
        ),
    ]
