# Generated by Django 4.2.20 on 2025-05-05 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picks', '0008_pickcomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpick',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='pick_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
