# Generated by Django 4.2.20 on 2025-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='이메일')),
                ('subject', models.CharField(max_length=128, verbose_name='제목')),
                ('message', models.TextField(default='', verbose_name='내용')),
            ],
        ),
    ]
