# Generated by Django 5.1.7 on 2025-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('category', models.CharField(choices=[('k-pop', 'K-POP'), ('R&B', 'R&B'), ('hiphop', '힙합'), ('pop', '팝'), ('etc', '기타')], default='etc', max_length=10, verbose_name='장르')),
                ('body', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
