# Generated by Django 5.1.7 on 2025-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='singer',
            field=models.CharField(default='Unknown', max_length=64, verbose_name='가수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('k-pop', 'K-POP'), ('R&B', 'R&B'), ('hiphop', '힙합'), ('pop', '팝'), ('rock', '락'), ('jazz', '재즈'), ('etc', '기타')], default='etc', max_length=10, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='노래'),
        ),
    ]
