# Generated by Django 4.2.20 on 2025-03-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0002_page_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='photo',
        ),
    ]
