# Generated by Django 4.2.20 on 2025-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0003_remove_page_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo', verbose_name='이미지'),
        ),
    ]
