# Generated by Django 5.1.7 on 2025-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='음악 제목')),
                ('singer', models.CharField(max_length=128, verbose_name='가수 이름')),
                ('body', models.TextField(default='', verbose_name='리뷰 작성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
